// LOCALHOST 
### 
GET http://localhost:8080/contacts
### 
GET http://localhost:8080/contacts/678b5e47abc15a4fab3cd9a4
### 
GET http://localhost:8080/

// PRODUCTION Deploy or render.com 
### 
GET https://cse341-heyrend.onrender.com
### 
GET https://cse341-heyrend.onrender.com 

### 
GET https://cse341-heyrend.onrender.com/contacts
### 
GET https://cse341-heyrend.onrender.com/contacts/678b5e47abc15a4fab3cd9a4